version: '3'

services: 
  db:
    image: mysql:8.0
    restart: always
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=iir_orientation_hw7
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: example_phpmyadmin
    ports:
        - 9999:80
    environment:
        - PMA_ARBITRARY=1

  web: 
    build: .
    command: ['/app/wait_for_it.sh', 'db:3306', '--', '/app/run.sh']
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"